Add cryptography chunk
This chunk needs to copy cffi into the build folder in order
to compile, if this is not done an error like the following
appears:

  error: Error: setup script specifies an absolute path:

      /usr/lib/python2.7/site-packages/cffi/__pycache__/_Cryptography_cffi_4ed9e37dx4000d087.c

  setup() arguments must *always* be /-separated paths relative to the
  setup.py directory, *never* absolute paths.